// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/correct": {
            "get": {
                "description": "Give correct",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pack"
                ],
                "summary": "Get Correct",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "X is number",
                        "name": "x",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/incorrect": {
            "get": {
                "description": "Give incorrect",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pack"
                ],
                "summary": "Get Incorrect",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "X is number",
                        "name": "x",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/set-sizes": {
            "post": {
                "description": "Set sizes for packs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pack"
                ],
                "summary": "Set sizes",
                "parameters": [
                    {
                        "description": "X is number",
                        "name": "sizes",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Pack-Service",
	Description:      "This is a sample server for a Gin application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
